services:
  - type: web
    name: ai-resume-evaluator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENROUTER_API_KEY_1
        sync: false
      - key: OPENROUTER_API_KEY_2
        sync: false
      - key: OPENROUTER_API_KEY_3
        sync: false
      - key: OPENROUTER_API_KEY_4
        sync: false
      - key: OPENROUTER_API_KEY_5
        sync: false 